export const CITY_LOCATIONS: Record<string, Record<string, string[]>> = {
    "Sakarya": {
        "Adapazarı": [
            "15 Temmuz Camili Mah.",
            "Abalı Mah.",
            "Acıelmalık Mah.",
            "Akıncılar Mah.",
            "Alandüzü Mah.",
            "Aşırlar Mah.",
            "Bağlar Mah.",
            "Bayraktar Mah.",
            "Bileciler Mah.",
            "Budaklar Mah.",
            "Büyükhataplı Mah.",
            "Çağlayan Mah.",
            "Çaltıcak Mah.",
            "Çamyolu Mah.",
            "Çelebiler Mah.",
            "Çerçiler Mah.",
            "Çökekler Mah.",
            "Çukurahmediye Mah.",
            "Cumhuriyet Mah.",
            "Dağdibi Mah.",
            "Demirbey Mah.",
            "Doğancılar Mah.",
            "Elmalı Mah.",
            "Evrenköy Mah.",
            "Göktepe Mah.",
            "Güllük Mah.",
            "Güneşler Merkez Mah.",
            "Güneşler Yeni Mah.",
            "Hacılar Mah.",
            "Hacıramazanlar Mah.",
            "Harmantepe Mah.",
            "Hızırtepe Mah.",
            "Ikizce Müslim Mah.",
            "Ikizce Osmaniye Mah.",
            "Ilyaslar Mah.",
            "Işıklar Mah.",
            "İstiklal Mah.",
            "Karadavutlu Mah.",
            "Karadere Mah.",
            "Karakamış Mah.",
            "Karaköy Mah.",
            "Karaman Mah.",
            "Karaosman Mah.",
            "Karapınar Mah.",
            "Kasımlar Mah.",
            "Kavaklıorman Mah.",
            "Kayrancık Mah.",
            "Kışla Mah.",
            "Kömürlük Mah.",
            "Köprübaşı Mah.",
            "Korucuk Mah.",
            "Küçükhataplı Mah.",
            "Kurtbeyler Mah.",
            "Kurtuluş Mah.",
            "Mahmudiye Mah.",
            "Maltepe Mah.",
            "Mithatpaşa Mah.",
            "Nasuhlar Mah.",
            "Örentepe Mah.",
            "Orta Mah.",
            "Ozanlar Mah.",
            "Papuççular Mah.",
            "Poyrazlar Mah.",
            "Rüstemler Mah.",
            "Sakarya Mah.",
            "Salmanlı Mah.",
            "Şeker Mah.",
            "Semerciler Mah.",
            "Şirinevler Mah.",
            "Solaklar Mah.",
            "Süleymanbey Mah.",
            "Taşkısığı Mah.",
            "Taşlık Mah.",
            "Tekeler Mah.",
            "Tepekum Mah.",
            "Tığcılar Mah.",
            "Turnadere Mah.",
            "Tuzla Mah.",
            "Yağcılar Mah.",
            "Yahyalar Mah.",
            "Yenicami Mah.",
            "Yenidoğan Mah.",
            "Yenigün Mah.",
            "Yeşilyurt Mah."
        ],
        "Akyazı": [
            "Akbalık Mah.",
            "Alaağaç Mah.",
            "Altındere Mah.",
            "Ballıkaya Mah.",
            "Batakköy Mah.",
            "Bedil Kazancı Mah.",
            "Bedilkadırbey Mah.",
            "Bediltahirbey Mah.",
            "Beldibi Mah.",
            "Bıçkıdere Mah.",
            "Boztepe Mah.",
            "Buğdaylı Mah.",
            "Çakıroğlu Mah.",
            "Çatalköprü Mah.",
            "Çıldırlar Mah.",
            "Cumhuriyet Mah.",
            "Dedeler Mah.",
            "Dokurcun Mah.",
            "Durmuşlar Mah.",
            "Düzyazı Mah.",
            "Erdoğdu Mah.",
            "Eskibedil Mah.",
            "Fatih Mah.",
            "Gazi Süleyman Paşa Mah.",
            "Gebeş Mah.",
            "Gökçeler Mah.",
            "Güvençler Mah.",
            "Güzlek Mah.",
            "Hanyatak Mah.",
            "Harunusta Mah.",
            "Hasanbey Mah.",
            "Hastahane Mah.",
            "Haydarlar Mah.",
            "İnönü Mah.",
            "Kabakulak Mah.",
            "Karaçalılık Mah.",
            "Kepekli Mah.",
            "Kızılcıkorman Mah.",
            "Konuralp Mah.",
            "Küçücek Cumhuriyet Mah.",
            "Küçücek İstiklal Mah.",
            "Kumköprü Mah.",
            "Kuzuluk Mah.",
            "Madenler Mah.",
            "Mansurlar Mah.",
            "Merkezyeniköy Mah.",
            "Ömercikler Mah.",
            "Osmanbey Mah.",
            "Pazarköy Mah.",
            "Reşadiye Mah.",
            "Salihiye Mah.",
            "Seyfeler Mah.",
            "Şerefiye Mah.",
            "Sukenarı Mah.",
            "Taşağıl Mah.",
            "Taşburun Mah.",
            "Taşyatak Mah.",
            "Topağaç Mah.",
            "Türkormanköy Mah.",
            "Uzunçınar Mah.",
            "Vakıf Mah.",
            "Yağcılar Mah.",
            "Yahyali Mah.",
            "Yeni Mah.",
            "Yenidoğan Mah.",
            "Yeniorman Mah.",
            "Yongalık Mah.",
            "Yörükyeri Mah.",
            "Yunus Emre Mah.",
            "Yuvalak Mah."
        ],
        "Arifiye": [
            "Adliye Mah.",
            "Ahmediye Mah.",
            "Arifbey Mah.",
            "Aşağı Kirazca Mah.",
            "Boğazköy Mah.",
            "Çaybaşı Fuadiye Mah.",
            "Çınardibi Mah.",
            "Cumhuriyet Mah.",
            "Fatih Mah.",
            "Hacıköy Mah.",
            "Hanlı Merkez Mah.",
            "Hanli Sakarya Mah.",
            "Hanlıköy Mah.",
            "Karaaptiler Mah.",
            "Karaçomaklar Mah.",
            "Kemaliye Mah.",
            "Kirazca Mah.",
            "Kışlaçay Mah.",
            "Kumbaşı Mah.",
            "Mollaköy Mah.",
            "Neviye Mah.",
            "Sakarya 1.Organize Sanayi Bölgesi Mah.",
            "Semerciler Mah.",
            "Türkçaybaşı Mah.",
            "Yukarıkirazca Mah."
        ],
        "Erenler": [
            "Alancuma Mah.",
            "Bağlar Mah.",
            "Bekirpaşa Mah.",
            "Büyükesence Mah.",
            "Çaybaşıyeniköy Mah.",
            "Çaykışla Mah.",
            "Değirmendere Mah.",
            "Dilmen Mah.",
            "Ekinli Mah.",
            "Emirler Mah.",
            "Epçeller Mah.",
            "Erenler Mah.",
            "Hacıoğlu Mah.",
            "Hasanbey Mah.",
            "Horozlar Mah.",
            "Hürriyet Mah.",
            "Kamışlı Mah.",
            "Kayalarmemduhiye Mah.",
            "Kayalarreşitbey Mah.",
            "Kozluk Mah.",
            "Küçükesence Mah.",
            "Küpçüler Mah.",
            "Nakışlar Mah.",
            "Pirahmetler Mah.",
            "Sarıcalar Mah.",
            "Şeyhköy Mah.",
            "Şükriye Mah.",
            "Tabakhane Mah.",
            "Tepe Mah.",
            "Tuapsalar Mah.",
            "Yazılı Mah.",
            "Yeni Mah.",
            "Yeşiltepe Mah."
        ],
        "Ferizli": [
            "Abdürrezzak Mah.",
            "Ağacık Mah.",
            "Akçukur Mah.",
            "Bakırlı Mah.",
            "Ceylandere Mah.",
            "Damlık Mah.",
            "Değirmencik Mah.",
            "Devlet Mah.",
            "Doğancı Mah.",
            "Ferizliosb Mah.",
            "Gölkent Mah.",
            "Hocaoğlu Mah.",
            "İnönü Mah.",
            "İstiklal Mah.",
            "Karadiken Mah.",
            "Kemalpaşa Mah.",
            "Kusca Mah.",
            "Nalköy Mah.",
            "Osmanağa Çiftliği Mah.",
            "Sarıahmetler Mah.",
            "Seyifler Mah.",
            "Sinanoğlu Mah.",
            "Teberik Mah.",
            "Tokat Mah.",
            "Yeni Mah."
        ],
        "Geyve": [
            "Ahibaba Mah.",
            "Akdoğan Mah.",
            "Akıncı Mah.",
            "Akkaya Mah.",
            "Alifuatpaşa Mah.",
            "Alıplar Mah.",
            "Aydınlar Mah.",
            "Bağcaz Mah.",
            "Bağlarbaşı Mah.",
            "Bayat Mah.",
            "Belpınar Mah.",
            "Bozören Mah.",
            "Burhaniye Mah.",
            "Camikebir Mah.",
            "Çamlık Mah.",
            "Çayköy Mah.",
            "Ceceler Mah.",
            "Çeltikler Mah.",
            "Çengel Mah.",
            "Çine Mah.",
            "Çukurköy Mah.",
            "Demirler Mah.",
            "Dereköy Mah.",
            "Doğançay Mah.",
            "Doğancıl Mah.",
            "Doğantepe Mah.",
            "Düzakçaşehir Mah.",
            "Epçeller Mah.",
            "Esenköy Mah.",
            "Eşme Mah.",
            "Fındıksuyu Mah.",
            "Gazi Süleyman Paşa Mah.",
            "Güney Mah.",
            "Günhoşlar Mah.",
            "Hacılar Mah.",
            "Hacıosmanlar Mah.",
            "Halidiye Mah.",
            "Hırka Mah.",
            "Hisarlık Mah.",
            "Ilıca Mah.",
            "İhsaniye Mah.",
            "İlimbey Mah.",
            "İnciksuyu Mah.",
            "Kamışlı Mah.",
            "Karacaören Mah.",
            "Karaçam Mah.",
            "Kızılkaya Mah.",
            "Koru Mah.",
            "Köprübaşı Mah.",
            "Kozan Mah.",
            "Kulfallar Mah.",
            "Maksudiye Mah.",
            "Melekşeoruç Mah.",
            "Melekşesolak Mah.",
            "Nuruosmaniye Mah.",
            "Orhaniye Mah.",
            "Örencik Mah.",
            "Poydular Mah.",
            "Sabırlar Mah.",
            "Safibey Mah.",
            "Saraçlı Mah.",
            "Sarıgazi Mah.",
            "Şehren Mah.",
            "Sekiharman Mah.",
            "Şerefiye Mah.",
            "Setçe Mah.",
            "Suçatı Mah.",
            "Sütalan Mah.",
            "Taşoluk Mah.",
            "Tepecikler Mah.",
            "Umurbey Mah.",
            "Yaylak Mah.",
            "Yörükler Mah."
        ],
        "Hendek": [
            "Akarca Mah.",
            "Akçayır Mah.",
            "Akova Mah.",
            "Akpınar Mah.",
            "Aksu Mah.",
            "Aktefek Mah.",
            "Aşağıçalıca Mah.",
            "Bakacak Mah.",
            "Balıklıihsaniye Mah.",
            "Başpınar Mah.",
            "Bayraktepe Mah.",
            "Beyköy Mah.",
            "Beylice Mah.",
            "Bıçkıatik Mah.",
            "Büyükdere Mah.",
            "Çakallık Mah.",
            "Çamlıca Mah.",
            "Çayırbaşı Mah.",
            "Çiftlik Mah.",
            "Çobanyatak Mah.",
            "Çukurhan Mah.",
            "Dereboğazı Mah.",
            "Dereköy Mah.",
            "Dikmen Mah.",
            "Esentepe Mah.",
            "Eskibıçkı Mah.",
            "Göksu Mah.",
            "Güldibi Mah.",
            "Gündoğan Mah.",
            "Güney Mah.",
            "Hacimbey Mah.",
            "Hacıkışla Mah.",
            "Halaç Mah.",
            "Hamitli Mah.",
            "Harmantepe Mah.",
            "Hicriye Mah.",
            "Hüseyinşeyh Mah.",
            "İkbaliye Mah.",
            "İkramiye Mah.",
            "Kadifekale Mah.",
            "Kahraman Mah.",
            "Kalayık Mah.",
            "Karadere Mah.",
            "Karatoprak Mah.",
            "Kargalı Hanbaba Mah.",
            "Kargalı Hanbabaosb Mah.",
            "Kargalıyeniköy Mah.",
            "Kazımiye Mah.",
            "Kemaliye Mah.",
            "Kırktepe Mah.",
            "Kızanlık Mah.",
            "Kocaahmetler Mah.",
            "Kocatöngel Mah.",
            "Köprübaşı Mah.",
            "Kurtköy Mah.",
            "Kurtuluş Mah.",
            "Lütfiyeköşk Mah.",
            "Mahmutbey Mah.",
            "Martinler Mah.",
            "Muradiye Mah.",
            "Necatipaşa Mah.",
            "Nuriye Mah.",
            "Paşaköy Mah.",
            "Pınarlı Mah.",
            "Puna Ortaköy Mah.",
            "Rasimpaşa Mah.",
            "Sarıdede Mah.",
            "Sarıyer Mah.",
            "Servetiye Mah.",
            "Şeyhler Mah.",
            "Sivritepe Mah.",
            "Sofular Mah.",
            "Soğuksu Mah.",
            "Sukenarı Mah.",
            "Süleymaniye Mah.",
            "Sümbüllü Mah.",
            "Turanlar Mah.",
            "Türbe Mah.",
            "Tuzak Mah.",
            "Uzuncaorman Mah.",
            "Uzunçarşı Mah.",
            "Yağbasan Mah.",
            "Yarıca Mah.",
            "Yayalar Mah.",
            "Yeni Mah.",
            "Yeniköy Mah.",
            "Yeniyayla Mah.",
            "Yeşilköy Mah.",
            "Yeşilvadi Mah.",
            "Yeşilyurt Mah.",
            "Yukarıçalıca Mah.",
            "Yukarıhüseyinşeyh Mah."
        ],
        "Karapürçek": [
            "Ahmediye Mah.",
            "Ahmetler Mah.",
            "Cumhuriyet Mah.",
            "Hocaköy Mah.",
            "İnönü Mah.",
            "Kanlıçay Mah.",
            "Kızılbayır Mah.",
            "Küçükkarapürçek Mah.",
            "Mecidiye Mah.",
            "Meşepınarı Mah.",
            "Mesudiye Mah.",
            "Teketaban Mah.",
            "Yazılıgürgen Mah.",
            "Yüksel Mah."
        ],
        "Karasu": [
            "Adatepe Mah.",
            "Akkum Mah.",
            "Ardıçbeli Mah.",
            "Aziziye Mah.",
            "Camitepe Mah.",
            "Çatalövez Mah.",
            "Darıçayırı Mah.",
            "Denizköy Mah.",
            "Gölköprü Mah.",
            "Hürriyet Mah.",
            "İhsaniye Mah.",
            "İncilli Mah.",
            "Kabakoz Mah.",
            "Kabakoz Osb Mah.",
            "Kancalar Mah.",
            "Karamüezzinler Mah.",
            "Karanlıkdere Mah.",
            "Karapınar Mah.",
            "Karasu Mah.",
            "Kızılcık Mah.",
            "Konacık Mah.",
            "Kurudere Mah.",
            "Kurumeşe Mah.",
            "Kuyumcullu Mah.",
            "Kuzuluk Mah.",
            "Limandere Mah.",
            "Manavpınarı Mah.",
            "Ortaköy Mah.",
            "Paralı Mah.",
            "Resuller Mah.",
            "Subatağı Mah.",
            "Taşlıgeçit Mah.",
            "Tepetarla Mah.",
            "Tuzla Mah.",
            "Üçoluk Mah.",
            "Yalı Mah.",
            "Yassıgeçit Mah.",
            "Yeni Mah.",
            "Yenidoğan Mah.",
            "Yeşilköy Mah.",
            "Yuvalıdere Mah."
        ],
        "Kaynarca": [
            "Akbaşlı Mah.",
            "Arifağa Mah.",
            "Başoğlu Mah.",
            "Birlik Mah.",
            "Büyükyanık Mah.",
            "Cebek Mah.",
            "Duduköy Mah.",
            "Eğrioğlu Mah.",
            "Gaziler Mah.",
            "Gölce Mah.",
            "Gürpınar Mah.",
            "Güven Mah.",
            "Hatipler Mah.",
            "İmamlar Mah.",
            "İşaret Mah.",
            "Kalburcu Mah.",
            "Karaçali Mah.",
            "Karamanlar Mah.",
            "Kayacık Mah.",
            "Kertil Mah.",
            "Kırktepe Mah.",
            "Kızılcaali Mah.",
            "Konak Mah.",
            "Kulaklı Mah.",
            "Küçükkaynarca Mah.",
            "Küçükkışla Mah.",
            "Merkez Mah.",
            "Müezzinler Mah.",
            "Okçular Mah.",
            "Ömerağa Mah.",
            "Orta Mah.",
            "Ortaköy Mah.",
            "Osmanlı Mah.",
            "Sabırlı Mah.",
            "Sarıbeyli Mah.",
            "Şeyhtımarı Mah.",
            "Taşoluk Mah.",
            "Topçu Mah.",
            "Turnalı Mah.",
            "Uğurlu Mah.",
            "Uzakkışla Mah.",
            "Uzunalan Mah.",
            "Yeniçam Mah.",
            "Yeşilova Mah.",
            "Ziahmet Mah."
        ],
        "Kocaali": [
            "Açmabaşı Mah.",
            "Ağalar Mah.",
            "Akpınar Mah.",
            "Aktaş Mah.",
            "Alandere Mah.",
            "Aydoğan Mah.",
            "Beyler Mah.",
            "Bezirgan Mah.",
            "Caferiye Mah.",
            "Çakmaklı Mah.",
            "Çukurköy Mah.",
            "Demiraçma Mah.",
            "Görele Mah.",
            "Gümüşoluk Mah.",
            "Hizar Mah.",
            "Kadıköy Mah.",
            "Karalar Mah.",
            "Karapelit Mah.",
            "Karşı Mah.",
            "Kestanepınarı Mah.",
            "Kirazlı Mah.",
            "Kızılüzüm Mah.",
            "Koğutpelit Mah.",
            "Köyyeri Mah.",
            "Kozluk Mah.",
            "Küplük Mah.",
            "Melen Mah.",
            "Merkez Mah.",
            "Selahiye Mah.",
            "Şerbetpınar Mah.",
            "Süngüt Mah.",
            "Yalı Mah.",
            "Yalpankaya Mah.",
            "Yanıksayvant Mah.",
            "Yayla Mah.",
            "Yeni Mah."
        ],
        "Pamukova": [
            "Ağaççılar Mah.",
            "Ahiler Mah.",
            "Akçakaya Mah.",
            "Bacıköy Mah.",
            "Bakacak Mah.",
            "Bayırakçaşehir Mah.",
            "Çardak Mah.",
            "Cihadiye Mah.",
            "Çilekli Mah.",
            "Cumhuriyet Mah.",
            "Eğriçay Mah.",
            "Elperek Mah.",
            "Eskiyayla Mah.",
            "Fevziye Mah.",
            "Gökgöz Mah.",
            "Hayrettin Mah.",
            "Hüseyinli Mah.",
            "İsabalı Mah.",
            "Kadıköy Mah.",
            "Karapınar Mah.",
            "Kazımiye Mah.",
            "Kemaliye Mah.",
            "Mekece Mah.",
            "Mesruriye Mah.",
            "Oruçlu Mah.",
            "Özbek Mah.",
            "Paşalar Mah.",
            "Pınarlı Mah.",
            "Şahmelek Mah.",
            "Şeyhvarmaz Mah.",
            "Teşvikiye Mah.",
            "Turgutlu Mah.",
            "Yenice Mah."
        ],
        "Sapanca": [
            "Akçay Mah.",
            "Balkaya Mah.",
            "Camicedit Mah.",
            "Çayiçi Mah.",
            "Fevziye Mah.",
            "Gazipaşa Mah.",
            "Göl Mah.",
            "Güldibi Mah.",
            "Hacımercan Mah.",
            "İkramiye Mah.",
            "İlmiye Mah.",
            "İstanbuldere Mah.",
            "Kırkpınar Hasanpaşa Mah.",
            "Kırkpınar Soğuksu Mah.",
            "Kırkpınar Tepebaşı Mah.",
            "Kurtköy Dibektaş Mah.",
            "Kurtköy Fatih Mah.",
            "Kurtköy Yavuzselim Mah.",
            "Kuruçeşme Mah.",
            "Mahmudiye Mah.",
            "Memnuniye Mah.",
            "Muradiye Mah.",
            "Nailiye Mah.",
            "Rüstempaşa Mah.",
            "Şükriye Mah.",
            "Ünlüce Mah.",
            "Uzunkum Mah.",
            "Yanık Mah.",
            "Yeni Mah."
        ],
        "Serdivan": [
            "Arabacıalanı Mah.",
            "Aralık Mah.",
            "Aşağıdereköy Mah.",
            "Bahçelievler Mah.",
            "Beşevler Mah.",
            "Beşköprü Mah.",
            "Çubuklu Mah.",
            "Dağyoncalı Mah.",
            "Esentepe Mah.",
            "Hamitabat Mah.",
            "İstiklal Mah.",
            "Kazımpaşa Mah.",
            "Kemalpaşa Mah.",
            "Kızılcıklı Mah.",
            "Köprübaşı Mah.",
            "Kuruçeşme Mah.",
            "Meşeli Mah.",
            "Orta Mah.",
            "Otuziki Evler Mah.",
            "Reşadiye Mah.",
            "Selahiye Mah.",
            "Uzunköy Mah.",
            "Vatan Mah.",
            "Yazlık Mah.",
            "Yukarıdereköy Mah."
        ],
        "Söğütlü": [
            "Akarca Mah.",
            "Akçakamış Mah.",
            "Akgöl Mah.",
            "Beşdeğirmen Mah.",
            "Cami Cedit Mah.",
            "Fındıklı Mah.",
            "Gündoğan Mah.",
            "Hasanfakı Mah.",
            "İmamlar Mah.",
            "Kantar Mah.",
            "Karateke Mah.",
            "Kurudil Mah.",
            "Küçük Söğütlü Mah.",
            "Levent Mah.",
            "Mağara Mah.",
            "Maksudiye Mah.",
            "Orta Mah.",
            "Rüstemler Mah.",
            "Sıraköy Mah.",
            "Soğucak Mah.",
            "Soğucak Osb Mah.",
            "Tokmaklıdere Mah.",
            "Türkbeylikkışla Mah.",
            "Yeniköy Mah."
        ],
        "Taraklı": [
            "Akçapınar Mah.",
            "Aksu Mah.",
            "Alballar Mah.",
            "Avdan Mah.",
            "Çamtepe Mah.",
            "Dışdedeler Mah.",
            "Duman Mah.",
            "Esenyurt Mah.",
            "Hacıaliler Mah.",
            "Hacımurat Mah.",
            "Hacıyakup Mah.",
            "Harkköy Mah.",
            "İçdedeler Mah.",
            "Kemaller Mah.",
            "Mahdumlar Mah.",
            "Pirler Mah.",
            "Tuzla Mah.",
            "Uğurlu Mah.",
            "Ulucamii Mah.",
            "Yenidoğan Mah.",
            "Yeniköy Mah.",
            "Yusufbey Mah."
        ]
    },
    "Kocaeli": {
        "Derince": [
            "Çavuşlu Mah.",
            "Çenedağ Mah.",
            "Çınarlı Mah.",
            "Deniz Mah.",
            "Dumlupınar Mah.",
            "Fatih Sultan Mah.",
            "Geredeli Mah.",
            "İbnisina Mah.",
            "Karagöllü Mah.",
            "Kaşıkçı Mah.",
            "Mersincik Mah.",
            "Sırrıpaşa Mah.",
            "Tahtalı Mah.",
            "Terziler Mah.",
            "Toylar Mah.",
            "Yavuz Sultan Mah.",
            "Yenikent Mah."
        ],
        "Kandıra": [
            "Ağaçaağıl Mah.",
            "Ahmethacılar Mah.",
            "Akbal Mah.",
            "Akçabeyli Mah.",
            "Akçakese Mah.",
            "Akçaova Mah.",
            "Akdurak Mah.",
            "Akıncı Mah.",
            "Alefli Mah.",
            "Antaplı Mah.",
            "Avdan Mah.",
            "Aydınlık Mah.",
            "Babaköy Mah.",
            "Babalı Mah.",
            "Bağırganlı Mah.",
            "Balaban Mah.",
            "Balcı Mah.",
            "Ballar Mah.",
            "Beyce Mah.",
            "Beylerbeyi Mah.",
            "Bolu Mah.",
            "Bozburun Mah.",
            "Çakırcaali Mah.",
            "Çakmaklar Mah.",
            "Çalca Mah.",
            "Çalköy Mah.",
            "Çalyer Mah.",
            "Çamkonak Mah.",
            "Çarşı Mah.",
            "Cebeci Mah.",
            "Çerçili Mah.",
            "Dalca Mah.",
            "Deliveli Mah.",
            "Doğancılı Mah.",
            "Döngelli Mah.",
            "Duraçalı Mah.",
            "Duraklı Mah.",
            "Eğercili Mah.",
            "Elmacık Mah.",
            "Esentepe Mah.",
            "Ferizli Mah.",
            "Gebeşler Mah.",
            "Goncaaydın Mah.",
            "Hacılar Mah.",
            "Hacımazlı Mah.",
            "Hacışeyh Mah.",
            "Hediyeli Mah.",
            "Hıdırlar Mah.",
            "Hüdaverdiler Mah.",
            "İncecik Mah.",
            "Kabaağaç Mah.",
            "Kanatlar Mah.",
            "Karaağaç Mah.",
            "Karadivan Mah.",
            "Karlı Mah.",
            "Kaymaz Erikli Mah.",
            "Kaymaz Mah.",
            "Kefken Mah.",
            "Kıncıllı Mah.",
            "Kırkarmut Mah.",
            "Kızılcapınar Mah.",
            "Kocakaymas Mah.",
            "Kubuzcu Mah.",
            "Kurtyeri Mah.",
            "Lokmanlı Mah.",
            "Mancarlar Mah.",
            "Merkez Erikli Mah.",
            "Mülküşehsuvar Mah.",
            "Nasuhlar Mah.",
            "Ömerli Mah.",
            "Orhan Mah.",
            "Özbey Mah.",
            "Pelitpınarı Mah.",
            "Pirceler Mah.",
            "Pınardüzü Mah.",
            "Pınarlı Mah.",
            "Safalı Mah.",
            "Sarıahmetler Mah.",
            "Sarıcaali Mah.",
            "Sarıgazi Mah.",
            "Sarnıçlar Mah.",
            "Selametli Mah.",
            "Selimköy Mah.",
            "Sepetçi Mah.",
            "Şerefsungur Mah.",
            "Seyitaliler Mah.",
            "Sinanlıbilallı Mah.",
            "Sucuali Mah.",
            "Süllü Mah.",
            "Tatarahmet Mah.",
            "Teksen Mah.",
            "Terziler Mah.",
            "Topluca Mah.",
            "Üğümce Mah.",
            "Yağcılar Mah.",
            "Yusufça Mah."
        ],
        "Gölcük": [
            "Atatürk Mah.",
            "Ayvazpınarı Mah.",
            "Çiftlik Mah.",
            "Cumhuriyet Mah.",
            "Değirmendere Merkez Mah.",
            "Değirmendere Yalı Mah.",
            "Deniz Evler Mah.",
            "Donanma Mah.",
            "Dumlupınar Mah.",
            "Düzağaç Mah.",
            "Eskiferhadiye Mah.",
            "Ferhadiye Mah.",
            "Halıdere Yalı Mah.",
            "Halıdere Yeni Mah.",
            "Hamidiye Mah.",
            "Hasaneyn Mah.",
            "Hisareyn Merkez Mah.",
            "İcadiye Mah.",
            "İhsaniye Merkez Mah.",
            "İpek Yolu Mah.",
            "İrşadiye Mah.",
            "Karaköprü Mah.",
            "Kavaklı Mah.",
            "Körfez Mah.",
            "Lütfiye Mah.",
            "Mamuriye Mah.",
            "Merkez Mah.",
            "Mesruriye Mah.",
            "Nimetiye Mah.",
            "Nüzhetiye Mah.",
            "Örcün Mah.",
            "Panayır Mah.",
            "Piyalepaşa Mah.",
            "Saraylı Mah.",
            "Şehitler Mah.",
            "Selimiye Mah.",
            "Şevketiye Mah.",
            "Şirinköy Mah.",
            "Siyretiye Mah.",
            "Sofular Mah.",
            "Topçular Mah.",
            "Ulaşlı Yalı Mah.",
            "Ulaşlı Yavuz Sultan Selim Mah.",
            "Ümmiye Mah.",
            "Yazlık Merkez Mah.",
            "Yazlık Yeni Mah.",
            "Yeni Mah.",
            "Yukarı Mah.",
            "Yunus Emre Mah.",
            "Yüzbaşılar Mah."
        ]
    },
    "Bilecik": {
        "Gölpazarı": [
            "Akçakavak Köyü",
            "Akçaöküz Mah. (Alıç Köyü)",
            "Aktaş Köyü",
            "Alıç Köyü",
            "Arıcaklar Köyü",
            "Armutçuk Köyü",
            "Bağışlar Mah. (Kavak Köyü)",
            "Bahçelievler Mah.",
            "Baltalı Köyü",
            "Bayat Köyü",
            "Bedi Köyü",
            "Bolatlı Köyü",
            "Bostancılar Mah. (İncirli Köyü)",
            "Büyükbelen Köyü",
            "Büyüksürmeli Köyü",
            "Büyüksusuz Köyü",
            "Cansızlar Mah. (Sarıhacılar Köyü)",
            "Çengeller Köyü",
            "Çiftlik Köyü",
            "Çımışkı Köyü",
            "Çukurören Köyü",
            "Demirhanlar Köyü",
            "Derecikören Köyü",
            "Dereli Damları Mah. (Dereli Köyü)",
            "Dereli Köyü",
            "Doğancılar Köyü",
            "Dokuz Köyü",
            "Dumanlar Mah. (Kümbet Köyü)",
            "Elmümin Mah. (Alıç Köyü)",
            "Gemici Mah. (Demirhanlar Köyü)",
            "Gökçeler Köyü",
            "Gökçeözü Köyü",
            "Göldağı Köyü",
            "Gözaçanlar Köyü",
            "Hacıdurmuşlar Mah. (Köprücek Köyü)",
            "Hacıköy Köyü",
            "Hamidiye Köyü",
            "İncirli Köyü",
            "İsmetpaşa Mah.",
            "İstiklal Mah.",
            "Karaağaç Köyü",
            "Karaahmetler Köyü",
            "Karacalar Köyü",
            "Kasımlar Köyü",
            "Keskin Köyü",
            "Köprücek Mah. (Köprücek Köyü)",
            "Küçüksusuz Köyü",
            "Küçükyenice Köyü",
            "Kümbet Köyü",
            "Kurşunlu Köyü",
            "Kuşçuören Köyü",
            "Muratlar Mah. (Kavak Köyü)",
            "Neçinler Mah. (Softalar Köyü)",
            "Ormancılar Mah. (Kavak Köyü)",
            "Orta Mah.",
            "Reşadiye Mah.",
            "Şahinler Köyü",
            "Sarıhacılar Köyü",
            "Seyfiler Mah. (Taşçıahiler Köyü)",
            "Şıhlar Mah. (Kavak Köyü)",
            "Softalar Köyü",
            "Söğütcük Köyü",
            "Taşçıahiler Mah. (Taşçıahiler Köyü)",
            "Tongurlar Köyü",
            "Türkmen Köyü",
            "Urancılar Mah. (Tongurlar Köyü)",
            "Üyük Köyü",
            "Yağcı Mah. (Dokuz Köyü)",
            "Yağcılar Mah. (Kavak Köyü)"
        ],
        "Söğüt": [
            "Akarbaşı Mah. (Çaltı Köyü)",
            "Akçasu Köyü",
            "Balaban Mah.",
            "Borcak Köyü",
            "Cumhuriyet Mah.",
            "Dereboyu Köyü",
            "Dömez Köyü",
            "Dudaş Köyü",
            "Geçitli Köyü",
            "Gündüzbey Köyü",
            "Gür Mah. (Çaltı Köyü)",
            "Hamitabat Köyü",
            "Hayriye Köyü",
            "Kayabalı Köyü",
            "Kayhan Mah.",
            "Kepen Köyü",
            "Kızilsaray Köyü",
            "Küreosb Mah. (Küre Köyü)",
            "Merkez Mah. (Küre Köyü)",
            "Oluklu Köyü",
            "Orta Mah.",
            "Ortaca Köyü",
            "Rızapaşa Köyü",
            "Savcıbey Köyü",
            "Şen Mah. (Çaltı Köyü)",
            "Sırhoca Köyü",
            "Türkmenbaşı Mah.",
            "Tuzaklı Köyü",
            "Yakacık Köyü",
            "Yeşilyurt Köyü",
            "Zemzemiye Köyü"
        ]
    },
    "Düzce": {
        "Çilimli": [
            "Alimler Mah. (Pırpır Köyü)",
            "Arabacı Mah.",
            "Bıçkıbaşı Köyü",
            "Çakallar Mah. (Pırpır Köyü)",
            "Çalılık Köyü",
            "Dikmeli Mah. (Dikmeli Köyü)",
            "Döngelli Köyü",
            "Esenli Köyü",
            "Gülebeler Mah. (Dikmeli Köyü)",
            "Hızardere Köyü",
            "İshaklar Köyü",
            "Kafyayla Köyü",
            "Kanal Mah. (Pırpır Köyü)",
            "Karaçörtlen Köyü",
            "Kavaklık Mah. (Kırkharman Köyü)",
            "Kiraztarla Köyü",
            "Kocaveliler Mah. (Pırpır Köyü)",
            "Kültür Mah. (Pırpır Köyü)",
            "Kuşoğlu Köyü",
            "Mahirağa Mah.",
            "Merkez Mah. (Alacamescit Köyü)",
            "Merkez Mah. (Dikmeli Köyü)",
            "Merkez Mah. (Kırkharman Köyü)",
            "Merkez Mah. (Yenivakıf Köyü)",
            "Ömercikler Mah. (Pırpır Köyü)",
            "Orman Mah. (Alacamescit Köyü)",
            "Orta Mah. (Pırpır Köyü)",
            "Sarımeşe Köyü",
            "Şerefiye Mah.",
            "Söğütlü Mah. (Söğütlü Köyü)",
            "Tepeköy Köyü",
            "Topçular Mah.",
            "Ulucami Mah.",
            "Yeni Mah. (Yenivakıf Köyü)",
            "Yeniköy Köyü",
            "Yeşil Mah.",
            "Yeşiltepe Mah.",
            "Yukarıkaraköy Köyü",
            "Yukarıköy Mah. (Kırkharman Köyü)"
        ]
    }
};

// Backward compatibility or legacy support
export const SAKARYA_LOCATIONS = CITY_LOCATIONS["Sakarya"];

export const CITIES = Object.keys(CITY_LOCATIONS).sort();

// Approximate center coordinates for each city/district
export const DISTRICT_CENTERS: Record<string, Record<string, { lat: number; lng: number }>> = {
    "Sakarya": {
        "Adapazarı": { lat: 40.6773, lng: 30.3963 },
        "Akyazı": { lat: 40.6830, lng: 30.6210 },
        "Arifiye": { lat: 40.6450, lng: 30.3650 },
        "Erenler": { lat: 40.6700, lng: 30.4200 },
        "Ferizli": { lat: 40.9390, lng: 30.4850 },
        "Geyve": { lat: 40.5100, lng: 30.2900 },
        "Hendek": { lat: 40.7930, lng: 30.7510 },
        "Karapürçek": { lat: 40.6400, lng: 30.5300 },
        "Karasu": { lat: 41.0950, lng: 30.6940 },
        "Kaynarca": { lat: 41.1580, lng: 30.3010 },
        "Kocaali": { lat: 41.0530, lng: 30.8530 },
        "Pamukova": { lat: 40.5060, lng: 30.1650 },
        "Sapanca": { lat: 40.6920, lng: 30.2700 },
        "Serdivan": { lat: 40.6930, lng: 30.3500 },
        "Söğütlü": { lat: 40.8980, lng: 30.4120 },
        "Taraklı": { lat: 40.3960, lng: 30.4900 },
    },
    "Kocaeli": {
        "Derince": { lat: 40.7561, lng: 29.8317 },
        "Kandıra": { lat: 41.0700, lng: 30.1500 },
        "Gölcük": { lat: 40.7167, lng: 29.8167 },
    },
    "Bilecik": {
        "Gölpazarı": { lat: 40.2667, lng: 30.3167 },
        "Söğüt": { lat: 40.0167, lng: 30.1833 },
    },
    "Düzce": {
        "Çilimli": { lat: 40.8833, lng: 31.0833 },
    }
};

// Legacy support
export const SAKARYA_DISTRICT_CENTERS = DISTRICT_CENTERS["Sakarya"];
